spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: 'singleD@!13'
    password: '@#$efwerR4'
    platform: org.hibernate.dialect.H2Dialect
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50